### ISSUE TITLE
undo examples change to match axis labels

### ISSUE THREAD

**Issue by pebau** [opengeospatial/coverage-implementation-schema#10]
The axis labels have changed in the examples to align with the current version of EPSG. This should be undone: 

- it is tentative that there is a deviation because it documents a way froward from a compatibility break that has been discussed at length between CRS.SWG and WCS.SWG earlier.

- Also, this matching is not necessary as per CIS 1.1.

There was long discusison about this. For the result see CIS 1.1 Req 5 and the pertaining discussion in the standard.

PS: might be good to make such work publicly known before commit, eg, on the mailing list, rather than having a small group deciding right in the meeting. That could unleash extra knowledge, such as in the case on hand. For example, I cannot participate in Coverages.SWWG telecons because it overlaps with lecture. However, I could contribute on email threads.

**Comment by jerstlouis** [comment]
@pebau Thanks for the feedback. We started looking at the PR #9 today but did not merge it yet, as we were discussing a few things, including that very topic. The commits are only in my own branch at this point, and I will amend them based on the discussions today, and you will have an opportunity to review them.

So what we discussed today in the SWG regarding Requirement 5 is that:
- The CIS 1.1.1 document (r8) is difficult to find. Both Google and the IS 1.1 link brings one to r6. We will take steps to try to remedy this.
- Requirement 5 completely removed the 3rd bullet point about axes having to match the CRS, while really only the part about the `name` and `axisAbbrev` matching is what should have been removed. We should review this so as not to rely only on the long _note_ to clearly understand the requirement.
- We should re-introduce clear language that the axes SHALL be matched by position in the requirement, which is only seen in the example below
- We discussed that although the name / axisAbbrev matching has been relaxed, we should re-introduce a recommendation (SHOULD) that the axes names should match the axisAbbrev. This still avoids the problem with the EPSG pulling the rug under our feet with an axisAbbrev change, while encouraging implementers to use axis naming consistent with the CRS rather than name them `Bob` or `a1` or `a2`.
- We also discussed that since we have this flexibility, we could look into possibly requesting to rename the badly named `ansi` and `unix` axisAbbrev of AnsiData and UnixTime, or otherwise including in the new recommendation exceptions for these to use `date` and `time` instead.

So I still think we should change the examples to use `Lon` rather than `Long`, but should keep `date` and `time`.
Many changes in the examples address actual issues regardless of all this.

**Comment by pebau** [comment]
AFAICS "date" is not a valid OGC time CRS. While naming an axis differently from axisAbbrev is possible as per CIS 1.1 this exactly violates the recommendation to use axisAbbrev.

If we want to see CRSs like "date" (which makes sense indeed, I'd welcome that) we should make a suggestion to OGC-NA, this has nothing to do with CIS.

**Comment by jerstlouis** [comment]
@pebau indeed "date" is not a time CRS, it's the axis label that I proposed to use for AnsiDate.

You probably saw in PR #12 (that you provided feedback on) that I suggested an explicit exception to that recommendation to use axisAbbrev for ansi->date and unix->time...

**Comment by pebau** [comment]
@jerstlouis yes, "date" is not a CRS indeed, my bad wording. Actually, data is sio generic and inexact that it is likely not a good choice. That said, "ansi" is not a good one either. I remember that way back there was already a discussion to change it, but it never happened. Now it is heavily in use and so cannot be deleted, but we could establish something better this time, maybe with some systematics that allows future time CRSs to fit in. (The Temporal.DWG had seen expectations on such a deliverable, but it did not happen either).

**Comment by jerstlouis** [comment]
Agreed to close in the SWG on 2021-05-12 once PR #12 is closed (now closed).
